### PR TITLE
Feature/fix eslint

### LINKED ISSUE #155: Introduce TypeScript and fix ESLint
# Summary 

TypeScript를 사용하여 기존의 prop-types를 대체하고 타입 안전성을 확보합니다.

# Tasks 

- [x] global state 타이핑
- [x] 각종 prop-types 오류 고치기

### PR DESCRIPTION
**Pull request by SnowSuno**
# Summary 

It closes #155. Fixes eslint issues that prevents build.

# Extra info 

n

# Images or Screenshots 

# Further Work

### CODE REVIEW

File: src/lib/interface/schemas/user.ts [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+  gender?: string;
+  birthday?: string;
+  flags?: string[];
+  firstName?: string;
+  lastName?: string;
+  koreanName?: string;
+  kaistId?: string;
+  sparcsId?: string;
+  facebookId?: string;
+  // TODO: check if typo
```
Comment (withSang) [inline src/lib/interface/schemas/user.ts:23]: 헉 나중에 이슈 만들게요!

**Review by withSang — APPROVED** [review]
고생하셨습니다 👍
